version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - '3000:3000'
    volumes:
      - '../www/html/frontend:/var/www/html/frontend'
    depends_on:
      - laravel-app
    networks:
      - app-network

  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - '../www/html/api-laravel:/var/www/html/api-laravel'
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - app-network

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - app-network

  db-test:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=laravel_test
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    ports:
      - 8085:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge
